/**
 * 站点级共享常量（客户端 / 服务端都能安全引用，不携带任何浏览器专用依赖）。
 *
 * 单独放一个文件的原因：`lib/export.ts` 顶部 import 了 html2canvas + jspdf
 * （纯客户端库）。`DISCLAIMER_LINE` / `WATERMARK_*` 被 `lib/reviewDoc.ts` 等
 * 也可能在服务端被引用的模块使用 —— 若它们直接从 export.ts 拿，会把 pdf 库
 * 一起拽进服务端 bundle。所以这些常量下沉到这里，export.ts 再从这转发出去。
 */

/** 导出件上的品牌水印（免费版去不掉，订阅后可移除） */
export const WATERMARK_TEXT = "aiwritereview.com";
export const WATERMARK_LINE = `Generated by AI Review Writer — ${WATERMARK_TEXT}`;

/**
 * 导出件上的免责声明。
 *
 * 措辞必须与站内、打印版逐字一致 —— 这份草稿会被拿去用于晋升/薪酬等雇佣决策，
 * 页面上写了「不能替代 HR/法律意见」而导出件上没写，等于把免责声明留在了
 * 唯一不重要的地方（用户在站内看到不代表 HR 看到）。
 */
export const DISCLAIMER_LINE =
  "AI-generated draft. Review and edit before use. Not a substitute for HR, legal, or employment advice.";
